/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register_design;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author enoke
 */
public class Decorations extends javax.swing.JFrame {

    /**
     * Creates new form Decorations
     */
    public Decorations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Stage = new javax.swing.JTextField();
        Wall = new javax.swing.JTextField();
        Food = new javax.swing.JTextField();
        Fabric = new javax.swing.JTextField();
        Expert = new javax.swing.JTextField();
        Ceiling = new javax.swing.JTextField();
        seating = new javax.swing.JTextField();
        Incorparate = new javax.swing.JTextField();
        Decorate = new javax.swing.JTextField();
        Flowers = new javax.swing.JTextField();
        Goody = new javax.swing.JTextField();
        Table = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(17, 9, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Stage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Stage, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 170, 60));

        Wall.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, 70));

        Food.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Food, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 170, 70));

        Fabric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Fabric, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 170, 70));

        Expert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Expert, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 170, 60));

        Ceiling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Ceiling, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 170, 60));

        seating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(seating, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 170, 60));

        Incorparate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Incorparate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, 60));

        Decorate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Decorate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 170, 60));

        Flowers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Flowers, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 170, 60));

        Goody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Goody, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 170, 60));

        Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 170, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 200, 225));
        jLabel1.setText("Wall Decorations");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 200, 225));
        jLabel2.setText("Food Display");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 200, 225));
        jLabel3.setText("Fabrics");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 200, 225));
        jLabel4.setText("Seating Arrangements");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 200, 225));
        jLabel5.setText("Ceiling");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 200, 225));
        jLabel6.setText("Expert Lightning");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 200, 225));
        jLabel7.setText("Incorparate Digital");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 200, 225));
        jLabel8.setText("Decorparate BackDrops");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 200, 225));
        jLabel9.setText("Stage Design");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 200, 225));
        jLabel10.setText("goody");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 200, 225));
        jLabel11.setText("Table Decorations");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 200, 225));
        jLabel12.setText("Flowers");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jButton1.setBackground(new java.awt.Color(58, 139, 182));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, -1, -1));

        jPanel2.setBackground(new java.awt.Color(60, 139, 182));

        jButton2.setText("Back");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Decorations");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("X");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            
            Connection cn = db.connector.getConnection();
            String sql = "insert into payment_method (Wall Decorations,Food Display,Fabrics,Seating Arrangements,Ceiling,Expert Lightning,Incorparate Digital,Decorparate BackDrops,Stage Design,goody,Table Decorations,Flowers) values(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1,Wall.getText());
            ps.setString(2,Food.getText());
            ps.setString(3,Fabric.getText());
            ps.setString(4,seating.getText());
            ps.setString(5,Ceiling.getText());
            ps.setString(6,Expert.getText());
            ps.setString(7,Incorparate.getText());
            ps.setString(8,Decorate.getText());
            ps.setString(9,Stage.getText());
            ps.setString(10,Goody.getText());
            ps.setString(11,Table.getText());
            ps.setString(12,Flowers.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this,"Saved SucessFully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menu_Form  Decorations = new Menu_Form();
        Decorations.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decorations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decorations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decorations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decorations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decorations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ceiling;
    private javax.swing.JTextField Decorate;
    private javax.swing.JTextField Expert;
    private javax.swing.JTextField Fabric;
    private javax.swing.JTextField Flowers;
    private javax.swing.JTextField Food;
    private javax.swing.JTextField Goody;
    private javax.swing.JTextField Incorparate;
    private javax.swing.JTextField Stage;
    private javax.swing.JTextField Table;
    private javax.swing.JTextField Wall;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField seating;
    // End of variables declaration//GEN-END:variables
}
