/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register_design;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import login_register_controller.EventFunctionController;

/**
 *
 * @author enoke
 */
public class Event_Functions extends javax.swing.JFrame {
    String getUserId;
    EventFunctionController e;
    /**
     * Creates new form Event_Functions
     */
    public Event_Functions() {
        initComponents();
        e = new EventFunctionController();
        Show_Users_In_JTable();
    }
    public Connection getConnection(){
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/users_db","root","");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
         
        
    }
    
    public void Show_Users_In_JTable(){
        ArrayList<Event_User> list = e.getUsersList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Users.getModel();
        Object[] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getType();
            row[2] = list.get(i).getName();
            row[3] = list.get(i).getVenue();
            row[3] = list.get(i).getAddress();
            row[3] = list.get(i).getCity();
            row[3] = list.get(i).getCustomerid();
            row[3] = list.get(i).getCustomerideas();
            
            model.addRow(row);
            
            
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_eventname = new javax.swing.JTextField();
        jTextField_venue = new javax.swing.JTextField();
        jTextField_eventaddress = new javax.swing.JTextField();
        jTextField_eventcity = new javax.swing.JTextField();
        jTextField_customerid = new javax.swing.JTextField();
        jComboBox_types = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField_customerideas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Users = new javax.swing.JTable();
        jButton_insert = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Back_Event = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Function");
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(17, 9, 48));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(931, 512));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 200, 225));
        jLabel1.setText("Event Type      :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 200, 225));
        jLabel2.setText("Event Id          :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 200, 225));
        jLabel3.setText("Event Name     :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 200, 225));
        jLabel4.setText("Event Venue    :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 200, 225));
        jLabel5.setText("Event Address  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 200, 225));
        jLabel6.setText("Event City        :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 200, 225));
        jLabel7.setText("CustomerId       :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jTextField_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(jTextField_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 210, -1));

        jTextField_eventname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jTextField_eventname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_eventnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_eventname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 210, -1));

        jTextField_venue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(jTextField_venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, -1));

        jTextField_eventaddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jTextField_eventaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_eventaddressActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_eventaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 210, -1));

        jTextField_eventcity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(jTextField_eventcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 210, -1));

        jTextField_customerid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(jTextField_customerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 210, -1));

        jComboBox_types.setBackground(new java.awt.Color(95, 210, 195));
        jComboBox_types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Conferences", "2.Seminars", "3.Meetings", "4.Team Building Meetings", "5.Trade show", "6.Business Dinners", "7.Golf Events", "8.Press Events", "9.Opening Ceremonies", "10.Product Launches", "11.Theme Parties", "12.VIP Events", "13.Trade Fairs", "14.ShareHolder Meetings", "15.Board Meetings", "16.Weedings", "17.Family Events", "18.Birthdays", " " }));
        jComboBox_types.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox_types.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_typesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_types, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 120, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 200, 225));
        jLabel8.setText("Customer Ideas :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jTextField_customerideas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 210, 195)));
        jPanel1.add(jTextField_customerideas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 220, 60));

        jTable_Display_Users.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 139, 182)));
        jTable_Display_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Event ID", "Event Type", "Event Name", "Event Venue", "Event Address", "Event City", "Customer ID", "Customer Ideas"
            }
        ));
        jTable_Display_Users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_Display_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Users);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 740, 100));

        jButton_insert.setBackground(new java.awt.Color(58, 139, 182));
        jButton_insert.setForeground(new java.awt.Color(255, 255, 255));
        jButton_insert.setText("INSERT");
        jButton_insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 80, 30));

        jButton_update.setBackground(new java.awt.Color(58, 139, 182));
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("UPDATE");
        jButton_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 80, 30));

        jButton_delete.setBackground(new java.awt.Color(58, 139, 182));
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setText("DELETE");
        jButton_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 80, 30));

        jPanel2.setBackground(new java.awt.Color(60, 139, 182));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        Back_Event.setBackground(new java.awt.Color(204, 204, 255));
        Back_Event.setText("Back");
        Back_Event.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        Back_Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_EventActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Event Function");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Back_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back_Event, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_typesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_typesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_typesActionPerformed

    private void jTextField_eventnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_eventnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_eventnameActionPerformed

    private void jTextField_eventaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_eventaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_eventaddressActionPerformed

    private void jTable_Display_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_UsersMouseClicked
        // TODO add your handling code here:
        int i = jTable_Display_Users.getSelectedRow();
        TableModel model = jTable_Display_Users.getModel();
        jTextField_id.setText(model.getValueAt(i,0).toString());
        jComboBox_types.setName(model.getValueAt(i,1).toString());
        jTextField_eventname.setText(model.getValueAt(i,2).toString());
        jTextField_venue.setText(model.getValueAt(i,3).toString());
        jTextField_eventaddress.setText(model.getValueAt(i,4).toString());
        jTextField_eventcity.setText(model.getValueAt(i,5).toString());
        jTextField_customerid.setText(model.getValueAt(i,6).toString());
        jTextField_customerideas.setText(model.getValueAt(i,7).toString());
        
    }//GEN-LAST:event_jTable_Display_UsersMouseClicked

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        // TODO add your handling code here:
        //String userid=new Login_Form().getUserId();
        //System.out.println(userid);
        String query = "INSERT INTO event "
                + "VALUES ('"+jTextField_id.getText()+"','"+jComboBox_types.getName()+"','A','axa','axa','axa','456','dss','34','sdd')";
        e.executeSQlQuery(query, "Inserted");
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE `event` SET `Event_type`='"+jComboBox_types.getName()+"',`Event_name`='"+jTextField_eventname.getText()+"',`Event_venue`='"+jTextField_venue.getText()+"',`Event_address`='"+jTextField_eventaddress.getText()+"',`Event_city`='"+jTextField_eventcity.getText()+"',`Customer_id`='"+jTextField_customerid.getText()+"',`Customer_ideas`='"+jTextField_customerideas.getText()+"' WHERE `Event_id` = "+jTextField_id.getText();
        e.executeSQlQuery(query,"updated");
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM `event` WHERE Event_id ="+jTextField_id.getText();
        e.executeSQlQuery(query,"Deleted");
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void Back_EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_EventActionPerformed
        // TODO add your handling code here:
         this.hide();
        Menu_Form sites = new Menu_Form();
        sites.setVisible(true);
    }//GEN-LAST:event_Back_EventActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Event_Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Event_Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Event_Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Event_Functions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Event_Functions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Event;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_types;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Users;
    private javax.swing.JTextField jTextField_customerid;
    private javax.swing.JTextField jTextField_customerideas;
    private javax.swing.JTextField jTextField_eventaddress;
    private javax.swing.JTextField jTextField_eventcity;
    private javax.swing.JTextField jTextField_eventname;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_venue;
    // End of variables declaration//GEN-END:variables
}
