/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_register_design;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import login_register_controller.Food_System_Controller;

/**
 *
 * @author enoke
 */
public class Food_System extends javax.swing.JFrame {

    /**
     * Creates new form Food_System
     */
    public Food_System() {
        initComponents();
        loadEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbEvent = new javax.swing.JComboBox<>();
        jCheckBox_package9 = new javax.swing.JCheckBox();
        jCheckBox_package1 = new javax.swing.JCheckBox();
        jCheckBox_package2 = new javax.swing.JCheckBox();
        jCheckBox_package3 = new javax.swing.JCheckBox();
        jCheckBox_package4 = new javax.swing.JCheckBox();
        jCheckBox_package5 = new javax.swing.JCheckBox();
        jCheckBox_package6 = new javax.swing.JCheckBox();
        jCheckBox_package7 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Back_Food = new javax.swing.JButton();
        jCheckBox_package8 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 40, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 100, 100));

        jPanel1.add(cbEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 240, 30));

        jCheckBox_package9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package9.setText("Package 9");
        jPanel1.add(jCheckBox_package9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, -1));

        jCheckBox_package1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package1.setText("Package 1");
        jCheckBox_package1.setBorderPainted(true);
        jCheckBox_package1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_package1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox_package1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jCheckBox_package2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package2.setText("Package 2");
        jPanel1.add(jCheckBox_package2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jCheckBox_package3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package3.setText("Package 3");
        jPanel1.add(jCheckBox_package3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jCheckBox_package4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package4.setText("Package 4");
        jPanel1.add(jCheckBox_package4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, -1));

        jCheckBox_package5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package5.setText("Package 5");
        jPanel1.add(jCheckBox_package5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jCheckBox_package6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package6.setText("Package 6");
        jPanel1.add(jCheckBox_package6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jCheckBox_package7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package7.setText("Package 7");
        jPanel1.add(jCheckBox_package7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Save");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 80));

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 80, 78));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 100, 100));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 100));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jLabel4.setText("jLabel4");
        jPanel12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 100, 100));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jPanel13.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jLabel5.setText("jLabel5");
        jPanel13.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 100, 100));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jPanel14.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 79, 78));

        jLabel6.setText("jLabel6");
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 100, 100));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jPanel15.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jLabel7.setText("jLabel7");
        jPanel15.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 100, 100));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton16.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jPanel16.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jLabel8.setText("jLabel8");
        jPanel16.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 100, 100));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\Downloads\\icons8-cursor-64.png")); // NOI18N
        jPanel17.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, 79, 78));

        jLabel10.setText("jLabel10");
        jPanel17.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 100, 100));

        Back_Food.setBackground(new java.awt.Color(204, 204, 255));
        Back_Food.setText("Back");
        Back_Food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_FoodActionPerformed(evt);
            }
        });
        jPanel1.add(Back_Food, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jCheckBox_package8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_package8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_package8.setText("Package 8");
        jPanel1.add(jCheckBox_package8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\enoke\\OneDrive\\Pictures\\foodd.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Package_1 package1 = new Package_1();
        package1.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Package_2 pack2 = new Package_2();
        pack2.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Package_3 pack3 = new Package_3();
        pack3.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jCheckBox_package1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_package1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckBox_package1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int pkg = 0;
        // for(int i = 0; i <10; i++  ){
        if (jCheckBox_package1.isSelected() || jCheckBox_package2.isSelected() || jCheckBox_package3.isSelected() || jCheckBox_package4.isSelected() || jCheckBox_package5.isSelected() || jCheckBox_package6.isSelected() || jCheckBox_package7.isSelected() || jCheckBox_package8.isSelected() || jCheckBox_package9.isSelected()) {
            ButtonGroup bg = new ButtonGroup();
            bg.add(jCheckBox_package1);
            bg.add(jCheckBox_package2);
            bg.add(jCheckBox_package3);
            bg.add(jCheckBox_package4);
            bg.add(jCheckBox_package5);
            bg.add(jCheckBox_package6);
            bg.add(jCheckBox_package7);
            bg.add(jCheckBox_package8);
            bg.add(jCheckBox_package9);

            if (jCheckBox_package1.isSelected()) {
                pkg = 1;
            }
            if (jCheckBox_package2.isSelected()) {
                pkg = 2;
            }
            if (jCheckBox_package3.isSelected()) {
                pkg = 3;
            }
            if (jCheckBox_package4.isSelected()) {
                pkg = 4;
            }
            if (jCheckBox_package5.isSelected()) {
                pkg = 5;
            }
            if (jCheckBox_package6.isSelected()) {
                pkg = 6;
            }
            if (jCheckBox_package7.isSelected()) {
                pkg = 7;
            }
            if (jCheckBox_package8.isSelected()) {
                pkg = 8;
            }
            if (jCheckBox_package9.isSelected()) {
                pkg = 9;
            }
            Food_System_Controller f = new Food_System_Controller();
            f.addPackage(pkg, Integer.parseInt(cbEvent.getSelectedItem().toString()));
        }

        // }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void Back_FoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_FoodActionPerformed
        // TODO add your handling code here:
        this.hide();
        Menu_Form frm = new Menu_Form();
        frm.setVisible(false);
    }//GEN-LAST:event_Back_FoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Food;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEvent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox_package1;
    private javax.swing.JCheckBox jCheckBox_package2;
    private javax.swing.JCheckBox jCheckBox_package3;
    private javax.swing.JCheckBox jCheckBox_package4;
    private javax.swing.JCheckBox jCheckBox_package5;
    private javax.swing.JCheckBox jCheckBox_package6;
    private javax.swing.JCheckBox jCheckBox_package7;
    private javax.swing.JCheckBox jCheckBox_package8;
    private javax.swing.JCheckBox jCheckBox_package9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void loadEvent() {
        try {
            Connection conn = db.connector.getConnection();
            String sql = "SELECT * FROM event";

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cbEvent.addItem(rs.getString(1));
            }
        } catch (Exception ex) {
            Logger.getLogger(Food_System.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
